# Generated by Django 5.2 on 2025-04-28 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norad_id', models.IntegerField(unique=True)),
                ('tle_line1', models.CharField(max_length=255)),
                ('tle_line2', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_time', models.DateTimeField()),
                ('min_distance_km', models.FloatField()),
                ('collision_risk', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('satellite1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_as_sat1', to='satellite_api.satellite')),
                ('satellite2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_as_sat2', to='satellite_api.satellite')),
            ],
        ),
    ]
