# Generated by Django 5.2 on 2025-04-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='color',
            field=models.CharField(default='#ff6e7f', max_length=16),
        ),
    ]
